[tool.black]
line-length = 120
extend-exclude = '''
(
   vwgconnect/_OLD_/
   | ^/*py$
)
'''
verbose = true

[tool.ruff]
line-length = 120
src = [ "vwgconnect" ]
force-exclude = true
extend-exclude = [ "vwgconnect/_OLD_/" ]
